server:
  port: 9003
  servlet:
    context-path: /qianbo-tcpserver
spring:
  application:
    name: qianbo-tcpserver
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10000
        max-idle: 0
        max-wait: -1ms
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        max-concurrency: 4
        acknowledge-mode: none
  datasource:
    url: jdbc:mysql://localhost:3306/qianbo?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 28740000
      connection-test-query: SELECT 1

#mybatis-plus 配置
mybatis-plus:
  type-aliases-package: com.qianb.mappoer
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false #关闭驼峰转下划线
    cache-enabled: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
common:
  socket:
    strategy: nio
    tcpPort: 9998
